### ISSUE TITLE
Clarify Readme Regarding :on Actions

### ISSUE THREAD

**Issue by seanahrens** [tute/merit#193]
In the Readme, under the Points heading, the following describes the :on parameter:

":on action as string or array of strings (similar to Rails routes)"

It would be helpful here to clarify if the argument is interpreted strictly as a controller + action as opposed to being model + method. It could be inferred that it's controller level, but it seems to me clarity could help.

Thanks for the gem!

**Comment by tute** [comment]
@seanahrens I'll leave this open until I make sure the README addresses these questions/answers. Hopefully this week. Thanks!

**Comment by seanahrens** [comment]
Ah, sorry for the premature close. I thought maybe you were waiting on my approval of some of the things mentioned. Should have asked and mentioned you. Cheers. (Keep up the good merit work. You impress me. I keep seeing pushes to this gem……..like you are a machine.)


On Wednesday, Jan 7, 2015 at 11:26 PM, Tute Costa <notifications@github.com>, wrote:
@seanahrens I'll leave this open until I make sure the README addresses these questions/answers. Hopefully this week. Thanks!
