### ISSUE TITLE
Sash_id not updating for user

### ISSUE THREAD

**Issue by dylanhusted** [tute/merit#208]
I'm trying to use Merit with my app, but current_user.points is returning 0 when it shouldn't. I believe this is because sash_id is nil for all of the users, but I'm not sure why that is.

What I've done so far:

1. gem 'merit'   # Gemfile
2. bundle
3. rails g merit:install
4. rails g merit user
5. bundle exec rake db:migrate
6. score 15, on: 'posts#create'      # app/models/merit/point_rules.rb

When I create a post: 

1. A record in merit_actions is created with the correct user_id, target model, and target_id. In addition, had_errors = false and processed = true. However, action_value = nil.
2. A record in merit_activity_logs is created with the correct action_id and a description of 'granted 15 points'.
3. A record in merit_score_points is created with a score_id and the correct num_points (15).
4. Not sure what is going on in merit_scores, but I 63 of them on only 7 actions.

When I call <%= current_user.points %> on my users show page, I get 0. When I call user.points in my console, I get 0. However, if I manually update the sash_id in my console, I get the correct number of points.

Why isn't sash_id updating, and is this the reason why current_user.points is returning 0?

Running on rails 4.0.5 and ruby 2.0.0

**Comment by tute** [comment]
What exactly do you mean, in code, when you say "manually update the sash_id in my console, I get the correct number of points"?

Can you share the code for your app?

**Comment by dylanhusted** [comment]
After creating a post in my app and entering the console:

2.0.0-p481 :001 > u = User.find(5)
  User Load (9.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 5]]
 => #<User id: 5, name: "Michael Jordan", email: "michaeljordan@yahoo.com", password_digest: "$2a$10$YYnTmgzzzN2uzJ8HbYhoX.icXDJUS8u8Vl8VSPZzfZaH...", admin: false, created_at: "2015-01-11 00:28:23", updated_at: "2015-01-11 00:28:25", remember_token: "0a02f12fe2ffbf0d54930177ecff388fc8671243", image: "Michael_Jordan_Net_Worth.jpg", sash_id: nil, level: 0>
2.0.0-p481 :002 > u.points
   (0.1ms)  begin transaction
  SQL (23.1ms)  INSERT INTO "sashes" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", Sun, 11 Jan 2015 23:04:34 UTC +00:00], ["updated_at", Sun, 11 Jan 2015 23:04:34 UTC +00:00]]
  SQL (0.2ms)  INSERT INTO "merit_scores" DEFAULT VALUES
  SQL (0.2ms)  UPDATE "merit_scores" SET "sash_id" = ? WHERE "merit_scores"."id" = 64  [["sash_id", 62]]
   (5.0ms)  commit transaction
   (0.1ms)  begin transaction
  User Exists (0.3ms)  SELECT 1 AS one FROM "users" WHERE (LOWER("users"."email") = LOWER('michaeljordan@yahoo.com') AND "users"."id" != 5) LIMIT 1
   (0.2ms)  rollback transaction
  Merit::Score Load (0.3ms)  SELECT "merit_scores".* FROM "merit_scores" WHERE "merit_scores"."sash_id" = ?  [["sash_id", 62]]
   (0.2ms)  SELECT SUM("merit_score_points"."num_points") AS sum_num_points, score_id AS score_id FROM "merit_score_points" WHERE "merit_score_points"."score_id" = ? GROUP BY score_id  [["score_id", 64]]
 => 0

The result is 0 points, but it should be 15. When I look through my database, I see that a record in merit_actions was created. A record was also created in merit_acvitivity_logs and merit_score_points. The new record in merit_score_points has a score_id of 61. In merit_scores, the record with an id of 61 has a sash_id of 59. So if I go back into console and manually give the user a sash_id of 59, this is what happens:

2.0.0-p481 :003 > u.sash_id = 59
 => 59
2.0.0-p481 :004 > u.points
  Merit::Sash Load (0.4ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = ? LIMIT 1  [["id", 59]]
  Merit::Score Load (0.2ms)  SELECT "merit_scores".* FROM "merit_scores" WHERE "merit_scores"."sash_id" = ?  [["sash_id", 59]]
   (0.2ms)  SELECT SUM("merit_score_points"."num_points") AS sum_num_points, score_id AS score_id FROM "merit_score_points" WHERE "merit_score_points"."score_id" = ? GROUP BY score_id  [["score_id", 61]]
 => 15

It returns 15, which is correct.

Thanks for the quick reply

**Comment by dylanhusted** [comment]
I just realized that "u.sash_id = 59" is not the correct command for updating attributes. Not sure how I forgot about 'update_attribute'. Here is how the console script should have been ran:

2.0.0-p481 :005 > u.update_attribute("sash_id", 15)
   (0.2ms)  begin transaction
  Merit::Sash Load (0.2ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = ? LIMIT 1  [["id", 59]]
  SQL (0.6ms)  UPDATE "users" SET "sash_id" = ?, "updated_at" = ? WHERE "users"."id" = 5  [["sash_id", 15], ["updated_at", Sun, 11 Jan 2015 23:11:14 UTC +00:00]]
   (40.3ms)  commit transaction
 => true
2.0.0-p481 :006 > u.points
  Merit::Sash Load (0.3ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = ? LIMIT 1  [["id", 15]]
  Merit::Score Load (0.1ms)  SELECT "merit_scores".* FROM "merit_scores" WHERE "merit_scores"."sash_id" = ?  [["sash_id", 15]]
   (0.1ms)  SELECT SUM("merit_score_points"."num_points") AS sum_num_points, score_id AS score_id FROM "merit_score_points" WHERE "merit_score_points"."score_id" = ? GROUP BY score_id  [["score_id", 15]]
 => 0

And the result is still 0. So I think my initial hunch about sash_ids was incorrect, but I still don't know why I keep getting 0 for user.points. I could share my code with you, are there any specific parts you are looking for? If not, I can add you to the project on github perhaps.

Let me know.

**Comment by tute** [comment]
Please share the app with me (add me to GitHub) so I can see if it's an app specific issue or the bug lives in merit. Thanks!

**Comment by dylanhusted** [comment]
@tute Just added you. Let me know if anything needs explanation!

**Comment by dylanhusted** [comment]
Also, the working being done with Merit is currently under the 'Merit-gem' branch

**Comment by tute** [comment]
The problem is in your `validates :password, length: { minimum: 6 }`, it should read: `validates :password, length: { minimum: 6 }, on: :create`.

Look why (this is using similar code as in merit internals):

```
irb(main):001:0> u = User.first
  User Load (0.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT 1
=> #<User id: 1, name: "t", email: "tutec@hotmail.com", password_digest: "$2a$10$.kBIln1psqdsMd.BFjlozeR7YvvFT3wBm92.MRVrqZk3...", admin: false, created_at: "2015-01-14 22:52:40", updated_at: "2015-01-14 22:52:40", remember_token: "27681fcd508c00b7ec7482cc4a52e6b91175ba54", image: nil, sash_id: nil, level: 0>
irb(main):003:0> u.update_attributes(sash: Merit::Sash.first)
  Merit::Sash Load (0.2ms)  SELECT "sashes".* FROM "sashes" ORDER BY "sashes"."id" ASC LIMIT 1
   (0.1ms)  begin transaction
  User Exists (0.1ms)  SELECT 1 AS one FROM "users" WHERE (LOWER("users"."email") = LOWER('tutec@hotmail.com') AND "users"."id" != 1) LIMIT 1
   (0.1ms)  rollback transaction
=> false
irb(main):004:0> u.errors
=> #<ActiveModel::Errors:0x007ff7cdf54638 @base=#<User id: 1, name: "t", email: "tutec@hotmail.com", password_digest: "$2a$10$.kBIln1psqdsMd.BFjlozeR7YvvFT3wBm92.MRVrqZk3...", admin: false, created_at: "2015-01-14 22:52:40", updated_at: "2015-01-14 22:52:40", remember_token: "27681fcd508c00b7ec7482cc4a52e6b91175ba54", image: nil, sash_id: 1, level: 0>, @messages={:password=>["is too short (minimum is 6 characters)"]}>
```

Can't update an invalid user, and every user is invalid after creation, according to your validation rule.

Best!

**Comment by dylanhusted** [comment]
Interesting, thanks for taking the time to find this!
