### ISSUE TITLE
user.has_badge?

### ISSUE THREAD

**Issue by seanahrens** [tute/merit#209]
What's the quickest way to determine if a user has a given badge? (given a badge "badge" and a user "user")

Currently I'm having to do some crazy hand-written iteration to do this seemingly simple task. Is there not a 

user.has_badge?(badge)

I'm trying things like user.badges.include?(badge) and I think ruby is doing a hash equals which is returning false, so I gotta do things like user.badges { |b| b.id = badge.id } with ambry. But now this is getting super complicated when I'm trying to find an intersection between the user's badges and a handful of badges (which badge the user has out of several).

**Comment by seanahrens** [comment]
@tute also feel free to slap me and tell me to post this to stackoverflow merit-gem.

**Comment by tute** [comment]
`user.badges` is indeed a Ruby array, and you can call `include?` on it as you would expect:

```ruby
b = Merit::Badge.find(5)
# => #<Merit::Badge id: 5, name: "relevant-commenter", level: nil, description: "You've received 5 votes on a comment.", custom_fields: nil>
u = User.first
# => #<User id: 1, name: "the-commenter-guy", created_at: "2014-09-14 14:37:38", updated_at: "2014-09-14 14:39:53", sash_id: 1, level: 0>
u.badges.include?(b)
# => true
u = User.last
# => #<User id: 5, name: "1", created_at: "2015-01-12 20:30:08", updated_at: "2015-01-12 20:30:08", sash_id: 13, level: 0>
u.badges.include?(b)
# => false
```

Closing as it doesn't seem like an issue in merit, happy to continue discussion.

**Comment by tute** [comment]
> an intersection between the user's badges and a handful of badges (which badge the user has out of several).

You should be able to use the `Array#&` intersection method for that.
