### ISSUE TITLE
Temporary badge not going away on Post delete

### ISSUE THREAD

**Issue by dylanhusted** [tute/merit#213]
Currently granting a badge for creating 1-14 posts:

```ruby
grant_on ['posts#create', 'posts#destroy'] badge_id: 2, temporary: true, to: :user do |post|
  @user = User.find(post.user_id)
  @user.posts.count >= 1 && @user.posts.count <= 14
end
```

When I create my first post, the badge is granted. Then, when I delete that post, the badge is still granted even though the user has 0 posts.

**Comment by tute** [comment]
I see a syntax error in your code (no comma between the array of actions and the `badge_id`).

Questions:

* What version of merit are you using?
* Do you define a `@post` instance variable on `PostController#destroy`?
* Can you post the log for create and destroy actions?

Thank you.

**Comment by dylanhusted** [comment]
Thanks for pointing out the comma error - looks like I need more sleep -.-

This fixed my issue, so I'll close it
