### ISSUE TITLE
Tutorial should mention that you can add has_merit to mongoid classes

### ISSUE THREAD

**Issue by simonv3** [tute/merit#214]
I didn't use the generators as they didn't work for me, but mimicking the dummy app seems to have everything working. The only thing that wasn't immediately obvious was the necessity for the has_merit indicator on the model.

I'd be happy to add this to the documentation, just wanted to make sure that I didn't miss anything.

**Comment by tute** [comment]
In step 3 of installation instructions (https://github.com/tute/merit#installation) we do say we need `has_merit` in the models. Do you think we can make it clearer?

Also, why didn't the generators work for you? Can you paste the output?

Thank you!

**Comment by simonv3** [comment]
@tute 

I can't seem to replicate the problem with the generator (it runs fine now), though our app doesn't generally use migrations yet. I ran it now and it seems to be fine.

If the generator is working fine, I guess it might not need to be expanded on. Maybe something like "The models that will have merit need to define `has_merit` on them."?

**Comment by tute** [comment]
I never heard of this issue before, so for now I'll consider it not a problem in merit, and if I hear this question again I'll work on improving the documentation. Thank you @simonv3 for your input.

**Comment by simonv3** [comment]
Sure, thanks for the quick support on this! Sorry I didn't keep better track of what went wrong.
